const actions = {
    RESET_STATE: 'RESET_STATE',
    SET_TEXT: 'SET_TEXT',
    SET_OUTGOING_VALUES: 'SET_OUTGOING_VALUES',
    SET_INCOMING_VALUES: 'SET_INCOMING_VALUES',
    SET_CURRENT_SYMBOL: 'SET_CURRENT_SYMBOL',
    WRONG_SYMBOL: 'WRONG_SYMBOL',
    RIGHT_SYMBOL: 'RIGHT_SYMBOL',
    SET_LENGTH: 'SET_LENGTH',
    START: 'START',
    SET_SPEED: 'SET_SPEED',
    SET_ACCURACY: 'SET_ACCURACY',
    SET_TYPED_TEXT: 'SET_TYPED_TEXT',
    SET_LANGUAGE: 'SET_LANGUAGE'
}
export default actions