const ACTIONS = {
    RESET_STATE: 'RESET_STATE',
    SET_TEXT: 'SET_TEXT',
    SET_RIGHT_KEY: 'SET_RIGHT_KEY',
    COMPLETE: 'COMPLETE',
    WRONG_SYMBOL: 'WRONG_SYMBOL',
    START: 'START',
    SET_SPEED: 'SET_SPEED',
    SET_ACCURACY: 'SET_ACCURACY',
    UPDATE_TYPED_TEXT: 'UPDATE_TYPED_TEXT',
    SET_LANGUAGE: 'SET_LANGUAGE'
}
export default ACTIONS